### PR TITLE
Add some slides on Sentinel processing in GRASS

### PR DESCRIPTION
**Pull request by griembauer**
This PR adds some generic slides (and screenshots) of GRASS addons for Sentinel-data including application examples.
Applications include:

- Nationwide land cover mapping: Here we calculated nationwide land cover maps from Sentinel-2 timeseries.
- Forest monitoring: Examples from the platform for ecosystem restoration HERMOSA: 
  - Small scale forest cover mapping (& monitoring by mapping changes between Sentinel-2 based time steps)
  - Mapping of vegetation dynamics using Sentinel-1 time-series
- Flood Mapping in Ecuador:
  - here we developed a flood mapping algorithm for Sentinel-1 scenes applying automatic thresholding and image segmentation
  - flood maps were generated for an entire year
  - flood frequency map shows how often individual pixels are classified as flooded --> in effect is is an empirical flood hazard map that can be used to inform disaster risk indicators (e.g. from the Sendai framework of disaster risk reduction)

### CODE REVIEW

**Comment by wenzeslaus** [comment]
@griembauer Can you please provide some key GRASS modules used for each of the Applications?

**Comment by griembauer** [comment]
I added the main GRASS modules in use for each of the Application slides. Unfortunately I cannot push to https://github.com/veroandreo/grass-gis-talks/pull/5, so that would have to be transferred manually...

**Comment by veroandreo** [comment]
> I added the main GRASS modules in use for each of the Application slides. Unfortunately I cannot push to #5, so that would have to be transferred manually...

Thanks Guido! I'll do that and merge. Sorry that I messed it up a lil bit :woman_facepalming:

**Comment by veroandreo** [comment]
I close this one, since the changes from this PR were included with minor modifications and merged in #5 

Thanks again @griembauer !

**Pull request closed without merging**
